---
env:
  node: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  sourceType: script
rules:
  indent: ["warn", 2]
  brace-style: off
  key-spacing: off
  comma-dangle: off
  no-constant-condition:
    - error
    - checkLoops: false
  space-before-function-paren: off
plugins:
  - jest
overrides:
  - files: "**/*-spec.js"
    extends:
    - "plugin:jest/recommended"
